resolver: lts-12.13

allow-newer: true

packages:
  - '.'
  - location:
      git: https://github.com/llvm-hs/llvm-hs-pretty
      commit: 0d04346

extra-deps:
  - megaparsec-7.0.0
  - llvm-hs-pure-7.0.0
  - llvm-hs-7.0.1

flags:
  llvm-hs:
    shared-llvm: true
